const TermsConditions = () => {
  return (
    <div className="mt-32">
      <div className="bg-white p-8 text-center border mb-6">
        <h1 className="text-4xl font-semibold mb-2">Terms & Conditions</h1>
        <span className="text-gray-600">Last Updated on April 08, 2025</span>
      </div>
      <div className="bg-accent py-8 md:px-16 px-4">
        <div className="flex flex-col gap-6 bg-white md:px-8 px-4 py-6 border">
          <div className="flex flex-col gap-4">
            <h4>
              <strong>Introduction</strong>
            </h4>
            <p>
              This document is an electronic record in terms of Information
              Technology Act, 2000 and rules thereunder as applicable and the
              amended provisions pertaining to electronic records in various
              statutes as amended by the Information Technology Act, 2000. This
              electronic record is generated by a computer system and does not
              require any physical or digital signatures.
            </p>
            <p>
              This document is published in accordance with the provisions of
              Rule 3 (1) of the Information Technology (Intermediaries
              guidelines) Rules, 2011 that require publishing the rules and
              regulations, privacy policy and Terms of Use for access or usage
              of domain name https://www.nourishnaturals.in/ ('Website'),
              including the related mobile site and mobile application
              (hereinafter referred to as 'Platform').
            </p>
            <p>
              The Platform is owned by NOURISH NATURALS, a company incorporated
              under the Companies Act, 1956 with its registered office at 245,
              BHAGWANPUR ROAD, Kishanpur Jamalpur RCP COLLEGE, Roorkee, India
              (hereinafter referred to as ‘Platform Owner’, 'we', 'us', 'our').
            </p>
          </div>

          <div className="flex flex-col gap-4">
            <h4>
              <strong>Terms of Use</strong>
            </h4>
            <p>
              Your use of the Platform and services and tools are governed by
              the following terms and conditions (“Terms of Use”) as applicable
              to the Platform including the applicable policies which are
              incorporated herein by way of reference. If You transact on the
              Platform, You shall be subject to the policies that are applicable
              to the Platform for such transaction. By mere use of the Platform,
              You shall be contracting with the Platform Owner and these terms
              and conditions including the policies constitute Your binding
              obligations, with Platform Owner.
            </p>
            <p>
              These Terms of Use relate to your use of our website, goods (as
              applicable) or services (as applicable) (collectively,
              'Services'). Any terms and conditions proposed by You which are in
              addition to or which conflict with these Terms of Use are
              expressly rejected by the Platform Owner and shall be of no force
              or effect.
            </p>
            <p>
              These Terms of Use can be modified at any time without assigning
              any reason. It is your responsibility to periodically review these
              Terms of Use to stay informed of updates.
            </p>
            <p>
              For the purpose of these Terms of Use, wherever the context so
              requires ‘you’, 'your' or ‘user’ shall mean any natural or legal
              person who has agreed to become a user/buyer on the Platform.
            </p>
            <p>
              ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR
              AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF
              USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
            </p>
          </div>

          <div className="flex flex-col gap-4">
            <h4>
              <strong>User Responsibilities</strong>
            </h4>
            <ul className="list-disc list-outside pl-8">
              <li>
                To access and use the Services, you agree to provide true,
                accurate and complete information to us during and after
                registration, and you shall be responsible for all acts done
                through the use of your registered account on the Platform.
              </li>
              <li>
                Your use of our Services and the Platform is solely and entirely
                at your own risk and discretion for which we shall not be liable
                to you in any manner. You are required to independently assess
                and ensure that the Services meet your requirements.
              </li>
              <li>
                You agree to pay us the charges associated with availing the
                Services.
              </li>
              <li>
                You agree not to use the Platform and/or Services for any
                purpose that is unlawful, illegal or forbidden by these Terms,
                or Indian or local laws that might apply to you.
              </li>
            </ul>
          </div>

          <div className="flex flex-col gap-4">
            <h4>
              <strong>Warranties and Liability</strong>
            </h4>
            <ul className="list-disc list-outside pl-8">
              <li>
                Neither we nor any third parties provide any warranty or
                guarantee as to the accuracy, timeliness, performance,
                completeness or suitability of the information and materials
                offered on this website or through the Services, for any
                specific purpose. You acknowledge that such information and
                materials may contain inaccuracies or errors and we expressly
                exclude liability for any such inaccuracies or errors to the
                fullest extent permitted by law.
              </li>
              <li>
                The contents of the Platform and the Services are proprietary to
                us and are licensed to us. You will not have any authority to
                claim any intellectual property rights, title, or interest in
                its contents. The contents includes and is not limited to the
                design, layout, look and graphics.
              </li>
              <li>
                You acknowledge that unauthorized use of the Platform and/or the
                Services may lead to action against you as per these Terms of
                Use and/or applicable laws.
              </li>
            </ul>
          </div>

          <div className="flex flex-col gap-4">
            <h4>
              <strong>Third Party Links</strong>
            </h4>
            <p>
              You agree and acknowledge that website and the Services may
              contain links to other third party websites. On accessing these
              links, you will be governed by the terms of use, privacy policy
              and such other policies of such third party websites. These links
              are provided for your convenience to provide further information.
            </p>
          </div>

          <div className="flex flex-col gap-4">
            <h4>
              <strong>Transactions</strong>
            </h4>
            <p>
              You understand that upon initiating a transaction for availing the
              Services you are entering into a legally binding and enforceable
              contract with the Platform Owner for the Services.
            </p>
          </div>

          <div className="flex flex-col gap-4">
            <h4>
              <strong>Indemnification</strong>
            </h4>
            <p>
              You shall indemnify and hold harmless Platform Owner, its
              affiliates, group companies (as applicable) and their respective
              officers, directors, agents, and employees, from any claim or
              demand, or actions including reasonable attorney's fees, made by
              any third party or penalty imposed due to or arising out of Your
              breach of this Terms of Use, privacy Policy and other Policies, or
              Your violation of any law, rules or regulations or the rights
              (including infringement of intellectual property rights) of a
              third party.
            </p>
          </div>

          <div className="flex flex-col gap-4">
            <h4>
              <strong>Force Majeure</strong>
            </h4>
            <p>
              Notwithstanding anything contained in these Terms of Use, the
              parties shall not be liable for any failure to perform an
              obligation under these Terms if performance is prevented or
              delayed by a force majeure event.
            </p>
          </div>

          <div className="flex flex-col gap-4">
            <h4>
              <strong>Governing Law and Dispute Resolution</strong>
            </h4>
            <ul className="list-disc list-outside pl-8">
              <li>
                These Terms and any dispute or claim relating to it, or its
                enforceability, shall be governed by and construed in accordance
                with the laws of India.
              </li>
              <li>
                All disputes arising out of or in connection with these Terms
                shall be subject to the exclusive jurisdiction of the courts in
                Roorkee, Uttarakhand.
              </li>
            </ul>
          </div>

          <div className="flex flex-col gap-4">
            <h4>
              <strong>Contact Information</strong>
            </h4>
            <p>
              All concerns or communications relating to these Terms must be
              communicated to us using the contact information provided on this
              website.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsConditions;
